"""颜色常量与渐变工具 — 向后兼容存根（从 src.tui.core 重新导出）

变更说明：颜色工具已迁移到 src/tui/core/gradient.py 和 src/tui/core/palettes.py，
          此文件保留为向后兼容存根。
"""
from __future__ import annotations

from ..core.constants import (
    GRAY, WHITE, CYAN, GREEN, YELLOW, RED, BLUE, MAGENTA,
    BOLD, DIM, RESET, ITALIC, UNDERLINE,
    BRIGHT_CYAN, BRIGHT_GREEN, BRIGHT_YELLOW, BRIGHT_BLUE,
    BRIGHT_MAGENTA, BRIGHT_RED, BRIGHT_WHITE, BRIGHT_BLACK,
    BG_BLUE, BG_CYAN, BG_GREEN, BG_YELLOW,
    ORANGE, TEAL, PINK, LAVENDER,
    SOFT_GREEN, SOFT_BLUE, SOFT_YELLOW, DARK_GRAY,
    GRAY_256, WHITE_256, CYAN_256, GREEN_256, YELLOW_256,
    RED_256, BLUE_256, MAGENTA_256,
    BRIGHT_CYAN_256, BRIGHT_GREEN_256, BRIGHT_YELLOW_256,
    BRIGHT_BLUE_256, BRIGHT_MAGENTA_256, BRIGHT_RED_256,
    BRIGHT_WHITE_256, BRIGHT_BLACK_256,
    BG_BLUE_256, BG_CYAN_256, BG_GREEN_256, BG_YELLOW_256,
    ORANGE_256, TEAL_256, PINK_256, LAVENDER_256,
    SOFT_GREEN_256, SOFT_BLUE_256, SOFT_YELLOW_256, DARK_GRAY_256,
    DIM_256,
)
from ..tui.core.gradient import hex_to_256, gradient_step, gradient_range
from ..tui.core.palettes import (
    GRADIENT_SUNSET, GRADIENT_OCEAN, GRADIENT_FOREST,
    GRADIENT_FIRE, GRADIENT_NEON,
    GRADIENT_AURORA, GRADIENT_CORAL, GRADIENT_MINT, GRADIENT_TWILIGHT,
    GRADIENT_SUNRISE, GRADIENT_PURPLE, GRADIENT_ICE,
    GRADIENT_SOFT, GRADIENT_EMERALD,
    GRADIENT_ROSE, GRADIENT_LAVA, GRADIENT_GLACIER,
    GRADIENT_SUNSET2, GRADIENT_NEON_GREEN, GRADIENT_NEON_PINK,
    GRADIENT_GOLD, GRADIENT_SKY, GRADIENT_MAGMA, GRADIENT_OCEAN_DEEP,
    BREATH_CYAN, BREATH_GREEN, BREATH_PURPLE, BREATH_GOLD, BREATH_ROSE,
)
from ..tui.core.ansi_utils import (
    strip_ansi, visual_width, truncate_ansi_visual,
    skip_ansi_sgr, truncate_ansi_sgr,
)
from ..tui.core.theme import THEME
from .console import get_console as _get_console

console = _get_console()

__all__: list[str] = [
    "THEME", "console",
    # ── 8-bit 颜色常量 ──
    "GRAY", "WHITE", "CYAN", "GREEN", "YELLOW", "RED", "BLUE", "MAGENTA",
    "BOLD", "DIM", "RESET", "ITALIC", "UNDERLINE",
    "BRIGHT_CYAN", "BRIGHT_GREEN", "BRIGHT_YELLOW", "BRIGHT_BLUE",
    "BRIGHT_MAGENTA", "BRIGHT_RED", "BRIGHT_WHITE", "BRIGHT_BLACK",
    "BG_BLUE", "BG_CYAN", "BG_GREEN", "BG_YELLOW",
    "ORANGE", "TEAL", "PINK", "LAVENDER",
    "SOFT_GREEN", "SOFT_BLUE", "SOFT_YELLOW", "DARK_GRAY",
    # ── 256 色常量 ──
    "GRAY_256", "WHITE_256", "CYAN_256", "GREEN_256", "YELLOW_256",
    "RED_256", "BLUE_256", "MAGENTA_256",
    "BRIGHT_CYAN_256", "BRIGHT_GREEN_256", "BRIGHT_YELLOW_256",
    "BRIGHT_BLUE_256", "BRIGHT_MAGENTA_256", "BRIGHT_RED_256",
    "BRIGHT_WHITE_256", "BRIGHT_BLACK_256",
    "BG_BLUE_256", "BG_CYAN_256", "BG_GREEN_256", "BG_YELLOW_256",
    "ORANGE_256", "TEAL_256", "PINK_256", "LAVENDER_256",
    "SOFT_GREEN_256", "SOFT_BLUE_256", "SOFT_YELLOW_256", "DARK_GRAY_256",
    # ── 渐变工具函数 ──
    "hex_to_256", "gradient_step", "gradient_range",
    # ── 预定义渐变调色板 ──
    "GRADIENT_SUNSET", "GRADIENT_OCEAN", "GRADIENT_FOREST",
    "GRADIENT_FIRE", "GRADIENT_NEON",
    "GRADIENT_AURORA", "GRADIENT_CORAL", "GRADIENT_MINT", "GRADIENT_TWILIGHT",
    "GRADIENT_SUNRISE", "GRADIENT_PURPLE", "GRADIENT_ICE",
    "GRADIENT_SOFT", "GRADIENT_EMERALD",
    # ── 第五阶段新增 ──
    "GRADIENT_ROSE", "GRADIENT_LAVA", "GRADIENT_GLACIER",
    "GRADIENT_SUNSET2", "GRADIENT_NEON_GREEN", "GRADIENT_NEON_PINK",
    "GRADIENT_GOLD", "GRADIENT_SKY", "GRADIENT_MAGMA", "GRADIENT_OCEAN_DEEP",
    # ── 双向呼吸调色板 ──
    "BREATH_CYAN", "BREATH_GREEN", "BREATH_PURPLE", "BREATH_GOLD", "BREATH_ROSE",
]
