"""杂项符号、重音映射、运算符字符、静默命令。"""

from __future__ import annotations

from typing import Dict, Set

_MISC_SYMBOLS: Dict[str, str] = {
    "infty": "∞", "emptyset": "∅", "varnothing": "∅",
    "nabla": "∇", "partial": "∂",
    "hbar": "ℏ", "ell": "ℓ", "imath": "ı", "jmath": "ȷ",
    "Re": "ℜ", "Im": "ℑ", "aleph": "ℵ", "wp": "℘",
    "angle": "∠", "measuredangle": "∡", "sphericalangle": "∢",
    "top": "⊤", "bot": "⊥",
    "therefore": "∴", "because": "∵",
    "dots": "…", "cdots": "⋯", "vdots": "⋮", "ddots": "⋱",
    "prime": "′", "backslash": "\\",
    "Box": "□", "Diamond": "◇", "square": "□", "diamond": "◇",
    "clubsuit": "♣", "diamondsuit": "♢", "heartsuit": "♥", "spadesuit": "♠",
    "colon": ":",
    "eth": "ð",
    "degree": "°", "textdegree": "°",
    "celsius": "℃", "micro": "µ", "ohm": "Ω",
    "permil": "‰", "AA": "Å", "aa": "å",
    "flat": "♭", "natural": "♮", "sharp": "♯",
    "mho": "℧", "Finv": "Ⅎ",
    "Bbbk": "𝕜",
    "checkmark": "✓",
    "pounds": "£", "yen": "¥",
    "Game": "⅁", "complement": "∁",
    "backepsilon": "∍",
    "between": "≬", "pitchfork": "⋔",
    "diagup": "╱", "diagdown": "╲",
    "blacksquare": "■", "blacktriangle": "▲", "blacktriangledown": "▼",
    "lozenge": "◊", "blacklozenge": "⧫",
    "bigstar": "★", "circledR": "®", "circledS": "Ⓢ",
    "circledast": "⊛", "circledcirc": "⊚", "circleddash": "⊝",
    "rightangle": "∟",
    "iddots": "⋰",
    "ulcorner": "⌜", "urcorner": "⌝", "llcorner": "⌞", "lrcorner": "⌟",
    "lgroup": "⟮", "rgroup": "⟯",
    "lmoustache": "⎰", "rmoustache": "⎱",
    "surd": "√",
    "neg": "¬",
    "slash": "∕",
    "P": "¶",
    "S": "§",
    "dag": "†",
    "ddag": "‡",
    "copyright": "©",
    "texttrademark": "™",
    "euro": "€",
    "cent": "¢",
    "ballot": "✗",
    "thorn": "þ",
    "dh": "ð",
    "hslash": "ℏ",
    "nexists": "∄",
    "lvertneqq": "≨",
    "gvertneqq": "≩",
    "o": "ø",
    "O": "Ø",
    "ae": "æ",
    "AE": "Æ",
    "oe": "œ",
    "OE": "Œ",
    "ss": "ß",
    "bigtriangleup": "△",
    "bigtriangledown": "▽",
    "blacktriangle": "▲",
    "blacktriangledown": "▼",
    "vartriangle": "△",
    "triangledown": "▽",
    "blacktriangleright": "▶",
    "blacktriangleleft": "◀",
    "triangleright": "▷",
    "triangleleft": "◁",
    "pentagon": "⬠",
    "hexagon": "⬡",
    "octagon": "⏹",
    "bigwhitestar": "☆",
    "bigblackstar": "★",
}

_ACCENT_MAP: Dict[str, str] = {
    "hat": "\u0302",
    "bar": "\u0304",
    "tilde": "\u0303",
    "vec": "\u20D7",
    "dot": "\u0307",
    "ddot": "\u0308",
    "widehat": "\u0302",
    "breve": "\u0306",
    "check": "\u030C",
    "grave": "\u0300",
    "acute": "\u0301",
    "mathring": "\u030A",
    "tilde": "\u0303",
}

# 运算符字符（在普通文本中检测为运算符样式）
_OPERATOR_CHARS: str = "+-−=<>|:!@#$%^&*~?/\\"

# 静默忽略的命令（排版提示类，终端渲染无实际效果）
_SILENT_COMMANDS: Set[str] = {
    "scriptstyle", "scriptscriptstyle",
    "nonumber", "notag",
    "label", "ref", "pageref",
    "vspace", "hspace", "hfil", "hfill", "vfil", "vfill",
    "small", "normalsize", "footnotesize",
    "large", "Large", "LARGE", "huge", "Huge",
    "centering", "raggedright", "raggedleft",
    "linebreak", "nolinebreak", "pagebreak", "nopagebreak",
    "enspace", "thinspace", "negthinspace",
    "medspace", "negmedspace", "thickspace", "negthickspace",
    "newline", "allowdisplaybreaks", "nobreak", "allowbreak",
    "strut",
    "hphantom", "vphantom", "phantom",
    "raisebox",
    "mathchoice",
    "kern", "mkern", "mskip",
    "definecolor",
    "intertext", "shortintertext",
    "hrule",
    "eqref",
}
