"""关系符号映射表。"""

from __future__ import annotations

from typing import Dict

_RELATION_SYMBOLS: Dict[str, str] = {
    "leq": "≤", "geq": "≥", "neq": "≠", "approx": "≈",
    "simeq": "≃", "cong": "≅", "equiv": "≡", "sim": "∼",
    "propto": "∝", "subset": "⊂", "supset": "⊃",
    "subseteq": "⊆", "supseteq": "⊇", "in": "∈", "notin": "∉",
    "ni": "∋", "forall": "∀", "exists": "∃", "nexists": "∄",
    "to": "→", "gets": "←",
    # 附加关系符号
    "ll": "≪", "gg": "≫",
    "prec": "≺", "succ": "≻",
    "preceq": "≼", "succeq": "≽",
    "doteq": "≐", "doteqdot": "≑",
    "fallingdotseq": "≒", "risingdotseq": "≓",
    "eqsim": "≂", "eqcirc": "≖",
    "triangleq": "≜",
    "nless": "≮", "ngtr": "≯",
    "nleq": "≰", "ngeq": "≱",
    "ncong": "≇", "nsim": "≁",
    "nsubseteq": "⊈", "nsupseteq": "⊉",
    "subsetneq": "⊊", "supsetneq": "⊋",
    "nvdash": "⊬", "nvDash": "⊭",
    "vdash": "⊢", "dashv": "⊣", "models": "⊧",
    "perp": "⊥", "parallel": "∥",
    "Dashv": "⫤", "Vdash": "⊩", "Vvdash": "⊪",
    "nVdash": "⊮", "nVDash": "⊯",
    "leftrightarrow": "↔", "Leftrightarrow": "⇔",
    "longleftrightarrow": "⟷", "Longleftrightarrow": "⟺",
    "longleftarrow": "⟵", "longrightarrow": "⟶",
    "looparrowleft": "↫", "looparrowright": "↬",
    "leftleftarrows": "⇇", "rightrightarrows": "⇉",
    "leftrightarrows": "⇆", "rightleftarrows": "⇄",
    "Lleftarrow": "⇚", "Rrightarrow": "⇛",
    "twoheadleftarrow": "↞", "twoheadrightarrow": "↠",
    "leftarrowtail": "↢", "rightarrowtail": "↣",
    "curvearrowleft": "↶", "curvearrowright": "↷",
    "triangleright": "▷", "triangleleft": "◁",
    "ntriangleleft": "⋪", "ntriangleright": "⋫",
    "ntrianglelefteq": "⋬", "ntrianglerighteq": "⋭",
    "trianglelefteq": "⊴", "trianglerighteq": "⊵",
    "nmid": "∤", "mid": "∣",
    "approxeq": "≊",
    "thicksim": "∼", "thickapprox": "≈",
    "Subset": "⋐", "Supset": "⋑",
    "smallfrown": "⌢", "smallsmile": "⌣",
    "multimap": "⊸",
    "leftrightsquigarrow": "↭",
    "uplus": "⊎",
    "sqcap": "⊓", "sqcup": "⊔",
    "sqsubseteq": "⊑", "sqsupseteq": "⊒",
    "bowtie": "⋈", "Join": "⋈",
    "Cup": "⋓", "Cap": "⋒",
    "dotplus": "∔",
    "ltimes": "⋉",
    "rtimes": "⋊",
    "leftthreetimes": "⋋",
    "rightthreetimes": "⋌",
    "curlywedge": "⋏",
    "curlyvee": "⋎",
    # === 补充的关系符号（amsmath/amssymb）===
    "napprox": "≉",
    "nparallel": "∦",
    "coloneqq": "≔",
    "eqqcolon": "≕",
    "subseteqq": "⫅",
    "supseteqq": "⫆",
    "subsetneqq": "⫋",
    "supsetneqq": "⫌",
    "lneqq": "≨",
    "gneqq": "≩",
    "lneq": "⪋",
    "gneq": "⪌",
    "lnsim": "⋦",
    "gnsim": "⋧",
    "lnapprox": "⪹",
    "gnapprox": "⪺",
    "nprec": "⊀",
    "nsucc": "⊁",
    "npreceq": "⋠",
    "nsucceq": "⋡",
    "precneqq": "⪵",
    "succneqq": "⪶",
    "precnapprox": "⪹",
    "succnapprox": "⪺",
    "precnsim": "⋨",
    "succnsim": "⋩",
    "varsubsetneq": "⊊",
    "varsupsetneq": "⊋",
    "varsubsetneqq": "⫋",
    "varsupsetneqq": "⫌",
    "dblcolon": "∷",
    "shortmid": "∣",
    "shortparallel": "∥",
    "nshortmid": "∤",
    "nshortparallel": "∦",
    "eqslantless": "⪕",
    "eqslantgtr": "⪖",
    "lesseqgtr": "⋚",
    "gtreqless": "⋛",
    "lesseqqgtr": "⪋",
    "gtreqqless": "⪌",
    "eqcolon": "∹",
    "colonapprox": "∶≈",
    "coloneq": "≔",
    "simneqq": "≆",
    "ngeqq": "≱",
    "nleqq": "≰",
    "ngeqslant": "⪈",
    "nleqslant": "⪇",
    # === LaTeX 常用短别名（\le/\ge/\ne/\lt/\gt）===
    "le": "≤",
    "ge": "≥",
    "ne": "≠",
    "lt": "<",
    "gt": ">",
    "lnot": "¬",
    "owns": "∋",
    # === 第二批补充（相似/大小/包含/三角关系，amsmath/amssymb 常用）===
    "isin": "∈",
    "lesssim": "≲",
    "gtrsim": "≳",
    "lessapprox": "⪅",
    "gtrapprox": "⪆",
    "lessgtr": "≶",
    "gtrless": "≷",
    "lessdot": "⋖",
    "gtrdot": "⋗",
    "lll": "⋘",
    "ggg": "⋙",
    "leqslant": "⩽",
    "geqslant": "⩾",
    "leqq": "≦",
    "geqq": "≧",
    "lvertneqq": "≨",
    "gvertneqq": "≩",
    "smile": "⌣",
    "frown": "⌢",
    "backsim": "∽",
    "backsimeq": "⋍",
    "precsim": "≾",
    "succsim": "≿",
    "curlyeqprec": "⋞",
    "curlyeqsucc": "⋟",
    "sqsubset": "⊏",
    "sqsupset": "⊐",
    "bumpeq": "≏",
    "Bumpeq": "≎",
    "lhd": "⊲",
    "rhd": "⊳",
    "unlhd": "⊴",
    "unrhd": "⊵",
    "vartriangleleft": "⊲",
    "vartriangleright": "⊳",
    "trianglelefteq": "⊴",
    "trianglerighteq": "⊵",
    "blacktriangleleft": "◀",
    "blacktriangleright": "▶",
    "ntrianglelefteq": "⋬",
    "ntrianglerighteq": "⋭",
    "gtreqless": "⋛",
    "lesseqgtr": "⋚",
    "doteqdot": "≑",
    "circeq": "≗",
    "triangleq": "≜",
    "eqslantgtr": "⪖",
    "eqslantless": "⪕",
    "nprec": "⊀",
    "nsucc": "⊁",
    "npreceq": "⋠",
    "nsucceq": "⋡",
    "precnsim": "⋨",
    "succnsim": "⋩",
    "lnsim": "⋦",
    "gnsim": "⋧",
    "varpropto": "∝",
    "Subset": "⋐",
    "Supset": "⋑",
    "subseteqq": "⫅",
    "supseteqq": "⫆",
    "nsubset": "⊄",
    "nsupset": "⊅",
    # === 第三批补充（KaTeX 全量关系符 / 冒号族 / 变体）===
    "vDash": "⊨",
    "VDash": "⊫",
    "Doteq": "≑",
    "asymp": "≍",
    "minuscolon": "∹",
    "minuscoloncolon": "−∷",
    "Eqcolon": "−∷",
    "colonequals": "≔",
    "colonminus": "≔",
    "Coloneq": "⩴", "Coloneqq": "⩴", "Colonqq": "⩴",
    "coloncolonequals": "⩴",
    "equalscolon": "≕",
    "Eqqcolon": "=∷", "equalscoloncolon": "=∷",
    "coloncolonapprox": "∷≈", "coloncolonsim": "∷∼",
    "Colonapprox": "∷≈", "Colonsim": "∷∼",
    "colonsim": "∶∼",
    "approxcolon": "≈∶", "approxcoloncolon": "≈∷",
    "simcolon": "∼∶", "simcoloncolon": "∼∷",
    "vcentcolon": "∶", "ratio": "∶",
    "sub": "⊂", "sube": "⊆", "supe": "⊇",
    "nsubseteqq": "⫅\u0338", "nsupseteqq": "⫆\u0338",
    "precapprox": "⪷", "succapprox": "⪸",
    "preccurlyeq": "≼", "succcurlyeq": "≽",
    "coloncolonminus": "−∷",
}
