"""向后兼容存根 — 从 engine/ 重导出。

原模块已迁移至 src/tui/engine/const.py。
"""

from __future__ import annotations

from ..engine.const import (
    RenderCommand,
    _MAIN_LABEL, _MAIN_SOURCE,
    _STYLE_DIM, _STYLE_FAIL, _STYLE_WARN, _STYLE_SUCCESS,
    _STYLE_ERROR, _STYLE_BOLD,
    _STYLE_ERROR_GRADIENT, _STYLE_USER_GRADIENT, _STYLE_NOTIFICATION_GRADIENT,
    _THINKING_HEADER,
    _CLEAR_PARSE_LINE, _THINKING_SEPARATOR,
    _MAX_ERROR_LENGTH, _MAX_OUTPUT_LEN,
    _RENDER_INTERVAL, _MAX_BATCH_SIZE,
    _ANSI_RED, _ANSI_YELLOW, _ANSI_RESET, _ANSI_CURSOR_BOTTOM,
    _DRAIN_LOCK_TIMEOUT,
)

__all__ = [
    "RenderCommand",
    "_MAIN_LABEL", "_MAIN_SOURCE",
    "_STYLE_DIM", "_STYLE_FAIL", "_STYLE_WARN", "_STYLE_SUCCESS",
    "_STYLE_ERROR", "_STYLE_BOLD",
    "_STYLE_ERROR_GRADIENT", "_STYLE_USER_GRADIENT", "_STYLE_NOTIFICATION_GRADIENT",
    "_THINKING_HEADER",
    "_CLEAR_PARSE_LINE", "_THINKING_SEPARATOR",
    "_MAX_ERROR_LENGTH", "_MAX_OUTPUT_LEN",
    "_RENDER_INTERVAL", "_MAX_BATCH_SIZE",
    "_ANSI_RED", "_ANSI_YELLOW", "_ANSI_RESET", "_ANSI_CURSOR_BOTTOM",
    "_DRAIN_LOCK_TIMEOUT",
]
