"""Protocol 定义层 — 跨层接口协议。

从 _components.py 拆分，将 Protocol 类与具体组件类分离，
避免接口定义与实现混杂。
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class BottomBarProtocol(Protocol):
    def increment_tool(self) -> None: ...
    def decrement_tool(self) -> None: ...
    def increment_tool_fail(self) -> None: ...
    def force_redraw(self) -> None: ...
    def sync_bottom_lines(self) -> None: ...
    @property
    def is_status_active(self) -> bool: ...
    def ensure_cursor_in_upper(self) -> None: ...
    def get_scroll_end(self) -> int: ...
    def get_cursor_info(self) -> tuple[str, int, int, int]: ...
    def compute_cursor_position(self, text: str, cursor_pos: int, h: int, w: int) -> tuple[int, int]: ...
    @property
    def is_completion_visible(self) -> bool: ...
    def hide_completions(self) -> None: ...
    def cycle_completion(self, delta: int) -> None: ...
    def show_completions(self, items: list[str], selected: int = 0, texts: list[str] | None = None, start_pos: int = 0, orig_prefix: str = "") -> None: ...
    def get_selected_completion(self) -> tuple[str, int, str]: ...
