"""向后兼容存根 — 从 animation/ 重导出。

原模块已迁移至 src/tui/animation/palettes.py（核心调色板常量）
和 src/tui/core/gradient.py（渐变工具函数）。
"""

from __future__ import annotations

from ..animation.palettes import (
    GRADIENT_SUNSET, GRADIENT_OCEAN, GRADIENT_FOREST,
    GRADIENT_FIRE, GRADIENT_NEON,
    GRADIENT_AURORA, GRADIENT_CORAL, GRADIENT_MINT, GRADIENT_TWILIGHT,
    GRADIENT_SUNRISE, GRADIENT_PURPLE, GRADIENT_ICE,
    GRADIENT_SOFT, GRADIENT_EMERALD,
    GRADIENT_ROSE, GRADIENT_LAVA, GRADIENT_GLACIER,
    GRADIENT_SUNSET2, GRADIENT_NEON_GREEN, GRADIENT_NEON_PINK,
    GRADIENT_GOLD, GRADIENT_SKY, GRADIENT_MAGMA, GRADIENT_OCEAN_DEEP,
    BREATH_CYAN, BREATH_GREEN, BREATH_PURPLE, BREATH_GOLD, BREATH_ROSE,
)

__all__ = [
    "GRADIENT_SUNSET", "GRADIENT_OCEAN", "GRADIENT_FOREST",
    "GRADIENT_FIRE", "GRADIENT_NEON",
    "GRADIENT_AURORA", "GRADIENT_CORAL", "GRADIENT_MINT", "GRADIENT_TWILIGHT",
    "GRADIENT_SUNRISE", "GRADIENT_PURPLE", "GRADIENT_ICE",
    "GRADIENT_SOFT", "GRADIENT_EMERALD",
    "GRADIENT_ROSE", "GRADIENT_LAVA", "GRADIENT_GLACIER",
    "GRADIENT_SUNSET2", "GRADIENT_NEON_GREEN", "GRADIENT_NEON_PINK",
    "GRADIENT_GOLD", "GRADIENT_SKY", "GRADIENT_MAGMA", "GRADIENT_OCEAN_DEEP",
    "BREATH_CYAN", "BREATH_GREEN", "BREATH_PURPLE",
    "BREATH_GOLD", "BREATH_ROSE",
]
